DROP TABLE IF EXISTS #;

CREATE TABLE # (a int NOT NULL PRIMARY KEY);

SET XACT_ABORT OFF; 

BEGIN TRAN
    INSERT INTO # (a) VALUES(1);
    INSERT INTO # (a) VALUES(2);
    INSERT INTO # (a) VALUES(2);
COMMIT;

SELECT * FROM #;